# Generated by Django 3.2.8 on 2021-10-11 23:02

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('ID_Pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('numero_cpf', cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='CPF')),
            ],
        ),
    ]
