# Generated by Django 3.2.8 on 2021-10-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('ID_Animal', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Pastor Alemao', 'Pastor Alemao'), ('Fila Brasileiro', 'Fila Brasileiro'), ('Pincher', 'Pincher')], max_length=100)),
                ('sexo', models.CharField(choices=[('MACHO', 'MACHO'), ('FEMEA', 'FEMEA')], max_length=100)),
                ('observacao', models.TextField(max_length=200)),
            ],
        ),
    ]
