# Generated by Django 3.2.8 on 2021-10-21 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_animal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='nome',
            new_name='animal',
        ),
    ]
