# Generated by Django 3.2.8 on 2021-10-21 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nome_animal_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanhoeTosa',
            fields=[
                ('ID_BanhoeTosa', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Banho', 'Banho'), ('Banho e Tosa Higienica', 'Banho e Tosa Higienica'), ('Bannho e Tosa', 'Bannho e Tosa')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='core.pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='banhoetosa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.banhoetosa'),
        ),
    ]
