# Generated by Django 3.2.8 on 2021-10-26 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20211020_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='ID_Animal',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='banhoetosa',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='animal',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('ID_longin', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
