# Generated by Django 3.1.7 on 2021-11-13 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cadastro_banhoetosa_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='category_Animal',
            field=models.CharField(choices=[('Pastor Alemao', 'Pastor Alemao'), ('Fila Brasileiro', 'Fila Brasileiro'), ('Pincher', 'Pincher')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo_Animal',
            field=models.CharField(choices=[('MACHO', 'MACHO'), ('FEMEA', 'FEMEA')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='banhoetosa_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.banhoetosa'),
            preserve_default=False,
        ),
    ]
